version: "3.9"

services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/srv/socialnet
      - static:/srv/socialnet/static
      - media:/srv/socialnet/media
    working_dir: /srv/socialnet/socialnet
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:17-alpine3.22
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env.dev

volumes:
  dev-db-data:
  media:
  static:
