version: "3.9"

services:
  api:
    container_name: socialnet_backend
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/srv/socialnet
      - ./api/socialnet/static:/srv/socialnet/static
      - ./api/socialnet/media:/srv/socialnet/media
    working_dir: /srv/socialnet/socialnet
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    networks:
      backend_net:
      socialnet_net:
        aliases:
          - api.local
    depends_on:
      - postgres_db
      - redis

  auth_proxy:
    build:
      context: ./auth_proxy
    container_name: auth_proxy
    volumes:
      - ./auth_proxy/:/srv/auth_proxy
    working_dir: /srv/auth_proxy
    command: >
      sh -c "flask run --host=0.0.0.0 --port=5000"
    ports:
      - "5000:5000"
    env_file:
      - .env.dev
    networks:
      socialnet_net:
        aliases:
          - proxy.local

  celery-default:
    build:
      context: ./api
    container_name: celery_default
    volumes:
      - ./api/:/srv/socialnet
      - ./api/socialnet/static:/srv/socialnet/static
      - ./api/socialnet/media:/srv/socialnet/media
    working_dir: /srv/socialnet/socialnet
    command: celery -A config worker -Q default -n worker_default@%h --loglevel=info
    env_file:
      - .env.dev
    depends_on:
      - postgres_db
      - redis
    restart: on-failure
    networks:
      - backend_net

  celery-media:
    build:
      context: ./api
    container_name: celery_media
    volumes:
      - ./api/:/srv/socialnet
      - ./api/socialnet/static:/srv/socialnet/static
      - ./api/socialnet/media:/srv/socialnet/media
    working_dir: /srv/socialnet/socialnet
    command: celery -A config worker -Q media -n worker_media@%h --loglevel=info
    env_file:
      - .env.dev
    depends_on:
      - postgres_db
      - redis
    restart: on-failure
    networks:
      - backend_net

  celery-follows:
    build:
      context: ./api
    container_name: celery_follows
    volumes:
      - ./api/:/srv/socialnet
      - ./api/socialnet/static:/srv/socialnet/static
      - ./api/socialnet/media:/srv/socialnet/media
    working_dir: /srv/socialnet/socialnet
    command: celery -A config worker -Q follows -n worker_follows@%h --loglevel=info
    env_file:
      - .env.dev
    depends_on:
      - postgres_db
      - redis
    restart: on-failure
    networks:
      - backend_net

  postgres_db:
    container_name: postgres_db
    image: postgres:17-alpine3.22
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    networks:
      - backend_net

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend_net

volumes:
  dev-db-data:

networks:
  backend_net:
    driver: bridge
  socialnet_net:
    driver: bridge