# Generated by Django 5.2.4 on 2025-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('premium', 'Premium'), ('guest', 'Guest')], default='user', max_length=20),
        ),
    ]
