# Generated by Django 5.2.5 on 2025-08-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
