# Generated by Django 5.2.5 on 2025-08-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_postimage_image_url_alter_userimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='user',
            new_name='owner',
        ),
    ]
